language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install --upgrade coverage coveralls nose
script: 
    - printenv PWD
    - pip install .
    - nosetests --with-doctest --with-coverage --cover-package=wos
after_success:
    coveralls
