dist: xenial  # Required for Python >= 3.7
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8-dev"
install:
    - pip install --upgrade pip setuptools coverage coveralls nose
script:
    - printenv PWD
    - pip install .
    - nosetests --with-doctest --with-coverage --cover-package=wos
after_success:
    coveralls
